name: Build App
on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: base
        environment-file: environment.yml

    - name: Install PyInstaller
      run: conda install -c conda-forge pyinstaller

    - name: Build App
      run: pyinstaller main.spec
