name: Run Test To Build
on:
  push:
    branches:
      - master

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Test
      run: python test.py
