name: Run Test To Build
on:
  push:
    branches:
      - master

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv  # Remplacez "myenv" par le nom de votre environnement Conda
        environment-file: environment.yml  # Si vous avez un fichier environment.yml spécifiant les dépendances

    - name: Install dependencies
      run: conda env update --file environment.yml && conda activate myenv

    - name: Run Test
      run: python test.py
